languages: [ru, uk]

processor:
  name: Калькулятор
  platform_version: '2.11'
  tests_file: tests/calculator_tests.yaml
  synonym: "Калькулятор | Калькулятор"

attributes:
  - name: Число1
    type: number
    digits: 15
    fraction_digits: 2
    synonym: "Число 1 | Число 1"
  - name: Число2
    type: number
    digits: 15
    fraction_digits: 2
    synonym: "Число 2 | Число 2"
  - name: Результат
    type: number
    digits: 15
    fraction_digits: 2
    synonym: "Результат | Результат"

forms:
  - name: Форма
    default: true
    elements:
      - type: InputField
        name: Число1
        attribute: Число1
      - type: InputField
        name: Число2
        attribute: Число2
      - type: InputField
        name: Результат
        attribute: Результат
    commands:
      - name: Добавить
        handler: Добавить
        title: "Сложить | Додати"
      - name: Вычесть
        handler: Вычесть
        title: "Вычесть | Відняти"
      - name: Умножить
        handler: Умножить
        title: "Умножить | Помножити"
