processor:
  name: ГенераторВизиток
  synonym:
    ru: Генератор визиток
    uk: Генератор візиток
attributes:
  - name: ФИО
    type: string
    title:
      ru: ФИО
      uk: ПІБ
  - name: Должность
    type: string
    title:
      ru: Должность
      uk: Посада
  - name: Телефон
    type: string
    title:
      ru: Телефон
  - name: Email
    type: string
    title:
      ru: Email
  - name: Компания
    type: string
    title:
      ru: Компания
      uk: Компанія
templates:
  - name: Card
    type: HTMLDocument
    file: templates/card.html
    auto_field: true
    field_name: CardPreview
    automation: templates/card.automation.yaml
forms:
  - name: Форма
    default: true
    elements:
      - type: UsualGroup
        name: ГруппаВвода
        group_type: UsualGroup
        representation: WeakSeparation
        child_items:
          - type: InputField
            name: ФИОПоле
            attribute: ФИО
            width: 40
          - type: InputField
            name: ДолжностьПоле
            attribute: Должность
            width: 40
          - type: InputField
            name: КомпанияПоле
            attribute: Компания
            width: 40
          - type: InputField
            name: ТелефонПоле
            attribute: Телефон
            width: 25
          - type: InputField
            name: EmailПоле
            attribute: Email
            width: 30
        title:
          ru: Данные визитки
          uk: Дані візитки
      - type: Button
        name: ОбновитьКнопка
        command: Обновить
        parent: ФормаКоманднаяПанель
    commands:
      - name: Обновить
        handler: Обновить
        picture: StdPicture.Refresh
        title:
          ru: Обновить визитку
          uk: Оновити візитку
    events:
      OnCreateAtServer: ПриСозданииНаСервере
