languages: [ru, uk, en]

processor:
  name: ПримерГрупповКолонок
  object_type: ExternalDataProcessor
  synonym: "Пример групп колонок | Приклад груп колонок | Column Groups Example"

attributes:
  - name: TotalDebit
    type: number
    synonym: "Всего дебет | Всього дебет | Total Debit"
  - name: TotalCredit
    type: number
    synonym: "Всего кредит | Всього кредит | Total Credit"

tabular_sections:
  - name: Operations
    synonym: "Операции | Операції | Operations"
    columns:
      - name: Operation
        type: string
        length: 150
        synonym: "Операция | Операція | Operation"
      - name: Date
        type: date
        synonym: "Дата | Дата | Date"
      - name: Time
        type: string
        length: 8
        synonym: "Время | Час | Time"
      - name: Debit
        type: number
        synonym: "Дебет | Дебет | Debit"
      - name: Credit
        type: number
        synonym: "Кредит | Кредит | Credit"
      - name: Total
        type: number
        synonym: "Итого | Підсумок | Total"
      - name: Status
        type: string
        length: 50
        synonym: "Статус | Статус | Status"

forms:
  - name: Форма
    default: true
    title: "Групування колонок таблиці | Групування колонок таблиці | Table Column Grouping"
    commands:
      - name: LoadData
        handler: LoadData
        picture: StdPicture.Refresh
        title: "Загрузить данные | Завантажити дані | Load Data"
      - name: Calculate
        handler: Calculate
        picture: StdPicture.GenerateReport
        title: "Рассчитать итоги | Розрахувати підсумки | Calculate Totals"
    elements:
      - type: LabelDecoration
        name: Instructions
        title: "Пример групування колонок таблиці:\n1. \"Дата і час\" - горизонтальна група з 2 колонок\n2. \"Суми\" - горизонтальна група з 3 колонок, вирівнювання Right\n3. \"Статус\" - окрема колонка поза групами\n"
        width: 80
      - type: Table
        name: OperationsTable
        tabular_section: Operations
        height: 15
        events:
          OnActivateRow: OperationsTableOnActivateRow
        elements:
          - type: LabelField
            name: Operation
            attribute: Operation
            width: 25
          - type: ColumnGroup
            name: DateTimeGroup
            group_layout: Horizontal
            show_in_header: true
            horizontal_align: Center
            title: "Дата и время | Дата і час | Date and Time"
            tooltip: "Дата и время операции | Дата і час операції | Operation date and time"
            elements:
              - type: LabelField
                name: Date
                attribute: Date
                width: 12
                title_location: None
              - type: LabelField
                name: Time
                attribute: Time
                width: 10
                title_location: None
          - type: ColumnGroup
            name: AmountsGroup
            group_layout: Horizontal
            show_in_header: true
            horizontal_align: Right
            title: "Суммы | Суми | Amounts"
            tooltip: "Дебет, Кредит и Итого | Дебет, Кредит та Підсумок | Debit, Credit and Total"
            elements:
              - type: LabelField
                name: Debit
                attribute: Debit
                width: 12
                title_location: None
              - type: LabelField
                name: Credit
                attribute: Credit
                width: 12
                title_location: None
              - type: LabelField
                name: Total
                attribute: Total
                width: 12
                title_location: None
          - type: LabelField
            name: Status
            attribute: Status
            width: 15
      - type: UsualGroup
        name: SummaryGroup
        show_title: true
        group_direction: Horizontal
        title: "Итоги | Підсумки | Totals"
        elements:
          - type: LabelDecoration
            name: TotalDebitLabel
            title: 'Всього дебет:'
            width: 15
          - type: InputField
            name: TotalDebit
            attribute: TotalDebit
            read_only: true
            width: 12
          - type: LabelDecoration
            name: TotalCreditLabel
            title: 'Всього кредит:'
            width: 15
          - type: InputField
            name: TotalCredit
            attribute: TotalCredit
            read_only: true
            width: 12
