processor:
  name: ПрикладВалидации
  platform_version: '2.18'
  synonym:
    ru: Пример расширенной валидации BSL
    uk: Приклад розширеної валідації BSL
validation:
  syntax_check_enabled: true
  check_thin_client: true
  check_server: true
  check_web_client: true
  check_external_connection: false
  check_thick_client: false
  semantic_check_enabled: true
  check_incorrect_references: true
  check_handlers_existence: true
  check_empty_handlers: true
  check_unreference_procedures: false
  check_extended_modules: true
attributes:
  - name: ТестовыйРеквизит
    type: string
    synonym:
      ru: Тестовый реквизит
      uk: Тестовий реквізит
  - name: Число
    type: number
    digits: 10
    fraction_digits: 2
    synonym:
      ru: Число
      uk: Число
  - name: Контрагент
    type: CatalogRef.Контрагенты
    synonym:
      ru: Контрагент
      uk: Контрагент

forms:
  - name: Форма
    default: true
    properties:
      title:
        ru: Пример валидации BSL
        uk: Приклад валідації BSL
      auto_title: false
    events:
      OnOpen: ПриОткрытии
    commands:
    - name: ВыполнитьКоманду
      handler: ВыполнитьКоманду
      shortcut: F5
      title:
        ru: Выполнить
        uk: Виконати
      tooltip:
        ru: Выполнить проверку
        uk: Виконати перевірку
    elements:
      - type: InputField
        name: ТестовыйРеквизитПоле
        attribute: ТестовыйРеквизит
      - type: InputField
        name: ЧислоПоле
        attribute: Число
      - type: InputField
        name: КонтрагентПоле
        attribute: Контрагент
      - type: Button
        name: ВыполнитьКнопка
        command: ВыполнитьКоманду
